compute_engine_instance:
  image_family: freebsd-14-0-snap
  cpu: 8
  memory: 4G

task:
  name: Test all packages in the PKG repository build
  setup_script:
  - uname -a
  - df -h
  - echo "Add Linux support to kernel 🐧"
  - kldload linux64
  - kldstat
  - mkdir -p /usr/local/etc/pkg/repos
  - cp ci/FreeBSD.conf /usr/local/etc/pkg/repos
  - mkdir -p /usr/ports/Keywords
  - cp ci/*.ucl /usr/ports/Keywords
  install_script:
  - pkg install -y git-lite icu libcjson librsvg2-rust libxcb mesa-libs pango pkgconf xcb xcb-util xcb-util-image xcb-util-wm
  script:
  - sh build.sh aquabsd.alps nvidia
  post_script:
  - ls -la .build/
  - df -h
  packages_artifacts:
    path: ".build/*"
